### ISSUE TITLE
Les épisodes apparaissent en ordre inverse

### ISSUE THREAD

**Issue by MartChic** [anisite/plugin.infologique.tou.tv#17]
Comme le titre le dit, les épisodes de séries apparaissent en ordre inverse, i.e. les premiers épisodes apparaissent en bas de la liste. De plus, ils ne sont pas numérotés.

**Comment by anisite** [comment]
Bonjour,

désolé du délai, j'ai été pas mal occupé par des urgences "COVID" bref, que la liste soit du plus récent au plus vieux est "by design" parce que ceux qui sont à jour dans une série (la plupart), n'ont pas à descendre en bas pour écouter le premier.

![image](https://user-images.githubusercontent.com/3194288/89474818-ab563600-d754-11ea-82b1-0a3e7a72e5e6.png)

par contre quand vous dites que ce n'est pas numéroté avez-vous une série en exemple ? 

Merci

**Comment by MartChic** [comment]
Par exemple les épisodes de la série "Surnaturel" ne sont pas numérotés. Mais c'est bon si on sait qu'ils sont toujours en ordre inverse.
